[theme]
primaryColor = "#ff4d00" # Coral/Laranja vibrante da Insigne
backgroundColor = "#ffffff" # Branco para um visual limpo (Clean)
secondaryBackgroundColor = "#f0f2f6" # Cinza claro para os menus
textColor = "#1e1e1e" # Grafite escuro para legibilidade
font = "sans serif"
